# Generated by Django 4.1 on 2022-08-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Ammunition',
            new_name='ammunition',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Food',
            new_name='food',
        ),
        migrations.AlterField(
            model_name='survivor',
            name='sex',
            field=models.CharField(choices=[('F', 'Feminine'), ('M', 'Masculine')], max_length=1),
        ),
        migrations.CreateModel(
            name='InfectedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report', models.DateTimeField(auto_now_add=True)),
                ('infected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.survivor')),
                ('informant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.survivor')),
            ],
            options={
                'unique_together': {('informant', 'infected')},
            },
        ),
    ]
