# Generated by Django 4.1 on 2022-08-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ammunition_inventory_ammunition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='is_infected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infectedreport',
            name='infected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='api.survivor'),
        ),
        migrations.AlterField(
            model_name='infectedreport',
            name='informant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.survivor'),
        ),
    ]
