# Generated by Django 4.1 on 2022-08-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_survivor_is_infected_alter_infectedreport_infected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survivor',
            old_name='sex',
            new_name='gender',
        ),
    ]
